### ISSUE TITLE
entirely fake server

### ISSUE THREAD

**Issue by DEERUX** [HirakoShiniji/Pixel-Worlds-Private-Server#2]
port seems legit as well as the tcp server which u pasted but the way u send packets is absolute garbage and i can tell its fake and garbage since:
- no use of bson objects
- pw expects VCheck as well. (which u dont do)
- not even sending to the main world selection menu screen
- no world sending, no compression library even included such as SevenZip
- no world breaking or placing
yeah keep calling others skid while u are one for sure u cant call this a private server its literally just garbage and fake/doesnt work.

**Comment by HirakoShiniji** [comment]
your private server based on my code. im closing the thread.

**Comment by DEERUX** [comment]
its not based on your code at all retard? lmao im not even using ur pasted tcp async shit and anyone can make a git that has some simple tcp setup and now u basically claim any tcp server on this earth is based on ur code? + none of my code is based on urs, havent even used a single thing from ur fake shit
